services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: irrigation-mqtt
    restart: unless-stopped

    ports:
      - "1883:1883"

    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

volumes:
  mosquitto-data:
  mosquitto-log: