<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
		<UserSecretsId>deea9b5b-b642-41bd-95e7-9e79121f15b8</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Application\Devices\NewFolder\**" />
		<Compile Remove="Infrastructure\NewFolder\**" />
		<Content Remove="Application\Devices\NewFolder\**" />
		<Content Remove="Infrastructure\NewFolder\**" />
		<EmbeddedResource Remove="Application\Devices\NewFolder\**" />
		<EmbeddedResource Remove="Infrastructure\NewFolder\**" />
		<None Remove="Application\Devices\NewFolder\**" />
		<None Remove="Infrastructure\NewFolder\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Ardalis.Specification" Version="9.3.1" />
		<PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="9.3.1" />
		<PackageReference Include="ErrorOr" Version="2.1.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.11" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Mediator.SourceGenerator" Version="3.0.*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Mediator.Abstractions" Version="3.0.*" />
		<PackageReference Include="MQTTnet" Version="5.2.0.1603" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Application\Activities\Events\" />
	  <Folder Include="Application\Devices\Commands\" />
	</ItemGroup>

</Project>